version: '3'

services:

  live-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: live-server public
    ports:
    - "8080:8080"
    working_dir: /app
    user: node
    volumes:
      - .:/app
      - yarn:/usr/local/share/.cache/yarn/v6

  transpile-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run transpile-watcher
    working_dir: /app
    volumes:
      - .:/app

  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - .:/app
      - yarn:/usr/local/share/.cache/yarn/v6

volumes:
  yarn: