version: '3'

services:

  dev-server:
    restart: always
    image: node:13-alpine3.10
    command: yarn run dev-server
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  node:
    restart: always
    image: node:13-alpine3.10
    command: tail -f /dev/null
    user: "${UID}:${GID}"
    working_dir: /app
    volumes:
      - .:/app
