version: '3'

services:

  dev-server:
    restart: always
    image: node:13-alpine3.11
    command: yarn run dev-server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  node:
    restart: always
    image: node:13-alpine3.11
    command: tail -f /dev/null
    working_dir: /app
    environment:
      - YARN_CACHE_FOLDER=/app/node_cache/yarn
    volumes:
      - .:/app
