version: "3"

services:
  web:
    restart: always
    image: node:16-alpine3.14
    command: yarn start
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
