name: build-check
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
