name: build-check
on:
  pull_request:
    branches: [main]
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: maker prettier
      - run: make build
