name: build-check
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn prettier
      - run: make build
