name: Check
on:
  pull_request:
    branches: [main]
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: make prettier
      - run: make build
