name: deploy
on:
  push:
    branches: [master, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: |
        echo ::set-env name=ID::$(id -u)
        echo ::set-env name=GID::$(id -g)
    - name: Build
      run: make build
    - name: Sync with S3
      run: aws s3 sync ./public s3://training-apps-rdok/indecision --delete
    - name: Invalidation CloudFront Distribution
      run: |
        INVALIDATION_ID=$(
          aws cloudfront create-invalidation  \
            --distribution-id "${DISTRIBUTION_ID}" \
            --paths /indecision/index.html /indecision/bundle.js \
            --query 'Invalidation.Id' \
            --output text
        )
        bash bin/wait-for-invalidation.sh "${DISTRIBUTION_ID}" "${INVALIDATION_ID}"
    - name: Check status
      uses: rdok/gh-actions-http-status@v1
      with:
        sites: '["https://rdok.co.uk/indecision/index.html"]'
        expected: '[201]'
