name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: |
        echo ::set-env name=ID::$(id -u)
        echo ::set-env name=GID::$(id -g)
    - name: Build
      run: |
        docker-compose run --rm node yarn
        docker-compose run --rm node yarn run transpile
    - name: Sync with bucket
      run: aws s3 sync ./public s3://indecision-rdok/public --exclude "*node_modules/*" --exclude "*.idea/*"  --exclude "*.git/*" --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
