name: deploy
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: "prod"
      url: "https://rdok.co.uk/indecision/index.html"
    concurrency: "prod"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Build & deploy static assets
        run: |
          make build
          aws s3 sync ./public s3://training-apps-rdok/indecision --delete
      - name: Invalidate CloudFront Distribution
        run: |
          INVALIDATION_ID=$(
            aws cloudfront create-invalidation  \
              --distribution-id "${DISTRIBUTION_ID}" \
              --paths /indecision/index.html /indecision/bundle.js \
              --query 'Invalidation.Id' \
              --output text
          )
          bash bin/wait-for-invalidation.sh "${DISTRIBUTION_ID}" "${INVALIDATION_ID}"
      - name: Check site status
        uses: rdok/http-status-action@v1
        with:
          sites: '["https://rdok.co.uk/indecision/index.html"]'
          expected: "[200]"
